### ISSUE TITLE
Latest combine-prs.yml seems broken?

### ISSUE THREAD

**Issue by lorennorman** [hrvey/combine-prs-workflow#15]
Just tried using your amazing Action for the first time, I copied the `.yml` file into my own project, pushed, and executed it from the Actions menu, as demonstrated in the README. However, I get an error (`state` is null), and when I inspect the code I can confirm that `state` is being passed into something before it is defined.

Here's the error I experienced if you'd like to see for yourself:
https://github.com/paperize/docs/actions/runs/3152233066/jobs/5127186452

I stepped back to the version of the yml file from 17 days ago, and it _almost_ worked, except that all of my PRs were returning a `pending` status. I loosened up the status check to just be "not `failed`", and got the whole thing working.

You've saved me so much time, thank you! Let me know if I can be of further assistance troubleshooting this bug.

**Comment by martingjaldbaek** [comment]
Hey, it sounds like maybe you don't have any checks set up to be run on your branches/PRs? At least that would explain why you get no state/the status API reports "pending". In that case, in the dialog that pops up before running the workflow, just enter false instead of true for the option called "Only combine PRs that are green (status is success)". That way the workflow won't try to read the (non-present) check status, so it should work. Let me know if that works!

If it works, then you can change the default for the option by editing the .yml file - it's called mustBeGreen, so if you change line 14 from true to false, it'll be off by default. That way you won't have to manually change the entry field to false every time you run the workflow :)

**Comment by lorennorman** [comment]
Brilliant, thank you!

**Comment by lorennorman** [comment]
Ok, that made a lot of sense to me. I decided adding a build check would be smarter than disabling the check altogether (may as well make sure the app builds without error!) and I'll give it a spin next time dependabot comes around making noise in my repo :)

Thank you! Closing this issue because I'm feeling confident you addressed the issue, but I'll come re-open and chat further if I have trouble. Happy coding!
